---
- name: Get prequisites
  get_url:
    url: "{{ item }}"
    dest: /tmp/
  with_items: 
    - "https://pkg.cfssl.org/R1.2/cfssl_linux-amd64"
    - "https://pkg.cfssl.org/R1.2/cfssljson_linux-amd64"
    - "https://storage.googleapis.com/kubernetes-release/release/v1.9.0/bin/linux/amd64/kubectl"
    - "https://github.com/coreos/etcd/releases/download/v3.2.11/etcd-v3.2.11-linux-amd64.tar.gz"
    - "https://storage.googleapis.com/kubernetes-release/release/v1.9.0/bin/linux/amd64/kube-apiserver"
    - "https://storage.googleapis.com/kubernetes-release/release/v1.9.0/bin/linux/amd64/kube-controller-manager"
    - "https://storage.googleapis.com/kubernetes-release/release/v1.9.0/bin/linux/amd64/kube-scheduler"
    - "https://github.com/containernetworking/plugins/releases/download/v0.6.0/cni-plugins-amd64-v0.6.0.tgz"
    - "https://github.com/kubernetes-incubator/cri-containerd/releases/download/v1.0.0-beta.0/cri-containerd-1.0.0-beta.0.linux-amd64.tar.gz"
    - "https://storage.googleapis.com/kubernetes-release/release/v1.9.0/bin/linux/amd64/kube-proxy"


- name: Extracting archives

- name: Install Rsync to copy large files on the right targets
  apt:
    name: rsync

- name: Preparing certificates files
  template:
    src: "{{ item }}"
    dest: "/tmp/{{ item }}"
  with_items:
    - ca-csr.j2
    - admin-csr.j2
    - kube-proxy-csr.j2
    - kubernetes-csr.j2

- name: Preparing certificates files of minions
  template:
    vars: 
      worker_node: "{{ item }}"
    src: "node-csr.j2"
    dest: "/tmp/{{ item }}-csr.json"
  with_items: groups.workers
