---
#- name: Kube dns
#  kubernetes:
#    api_endpoint: "{{ master_ip }}"
#    insecure: true
#    file_reference: /tmp/kube-dns.yaml
#    state: present

#- name: Kube dns
#  shell: "kubectl create -f /tmp/kube-dns.yaml"
#  when: dns_addon
- name: Kube dns
  command: kubectl create -f /tmp/coredns.yaml --kubeconfig=/tmp/k8s-config
  when: dns_addon
  delegate_to: "{{ groups['masters'][0] }}"
