---
- name: Install Socat
  apt:
    name: socat

- name: Install docker
  apt:
    name: docker

- name: daemon_reload
  systemd: 
    daemon_reload: yes

- name: Start services
  service: 
    name: "{{ item }}"
    enabled: yes
    state: started
  with_items:
    - containerd
    - cri-containerd
    - kubelet
    - kube-proxy