---
- name: Ensures /var/lib/kubernetes/ dir exists on Master(s)
  file: 
    path=/var/lib/kubernetes/
    state=directory

- name: Copying cert files on master(s)
  template: 
    src: "/tmp/{{ item }}"
    dest: "/var/lib/kubernetes/{{ item }}"
  with_items:
    - ca.pem
    - ca-key.pem
    - kubernetes-key.pem
    - kubernetes.pem
    - encryption-config.yaml

- name: Copying Kube files on master(s)
  template: 
    src: "/tmp/{{ item }}"
    dest: "/usr/local/bin/{{ item }}"
  with_items:
    - ca.pem
    - ca-key.pem
    - kubernetes-key.pem
    - kubernetes.pem