---
- name: Ensures /var/lib/kubernetes/ dir exists on Master(s)
  file: 
    path=/var/lib/kubernetes/
    state=directory

- name: Copying cert files on master(s)
  copy: 
    src: "/tmp/{{ item }}"
    dest: "/var/lib/kubernetes/{{ item }}"
  with_items:
    - ca.pem
    - ca-key.pem
    - kubernetes-key.pem
    - kubernetes.pem
    - encryption-config.yaml

- name: Copying Kube files on master(s)
  copy: 
    src: "/tmp/{{ item }}"
    dest: "/usr/local/bin/{{ item }}"
  with_items:
    - kube-apiserver
    - kube-controller-manager
    - kube-scheduler
    - kubectl

- name: Copying Apiserver service file on Master(s)
  template: 
    src: "kube-apiserver-service.j2"
    dest: "/etc/systemd/system/kube-apiserver.service"

- name: Copying kube-controller-manager service file on Master(s)
  template: 
    src: "kube-controller-manager-service.j2"
    dest: "/etc/systemd/system/kube-controller-manager.service"

- name: Copying kube-scheduler service file on Master(s)
  template: 
    src: "{{ role_path }}/files/kube-scheduler.service"
    dest: "/etc/systemd/system/kube-scheduler.service"