---
# Global variables that can 
# be included in a task with 
#  include_vars: "{{ playbook_dir }}/config.yaml"
################################################

#
## Essential network variables ##
#
master_ip: 11.11.11.11  # Also known as API Endpoint
service_ip: 85.85.0.0/16 # Why 85 ? Because it looks like 8s in k8s ;-)
dns_addon: True #Or false if you don't want the DNS cluster add-on
cluster_dns: 85.85.85.85  
cluster_cidr: 172.168.0.0/16
#
## Misc for certificates
#
cluster_name: MyK8sCluster
country: the
locality: automated
organization: way
organizationalUnit : in
state: ansible

