---
# Global variables that can 
# be included in a task with 
#  include_vars: "{{ playbook_dir }}/config.yaml"
################################################

#
## Versions of components
#
k8s_version: v1.16.2 #https://github.com/kubernetes/kubernetes/releases
etcd_version: v3.4.2 #https://github.com/etcd-io/etcd/releases
cni_plugin_version: v0.8.2 #https://github.com/containernetworking/plugins/releases
cri_tools_version: v1.16.1 #https://github.com/kubernetes-sigs/cri-tools/releases
runc_version: v1.0.0-rc9 #https://github.com/opencontainers/runc/releases
containerd_version: 1.3.0 #https://github.com/containerd/containerd/releases
istio_version: 1.2.2 #https://github.com/istio/istio/releases
#cilium_version: 1.5.4 #https://github.com/cilium/cilium/releases - Not implemented
#
## Essential network variables ##
#
master_ip: 111.111.111.111  # Also known as API Endpoint
add_dummy0_master_ip: True #If you're using BGP to announce your api server address
service_ip: 85.85.0.0/16 # Why 85 ? Because it looks like 8s in k8s ;-)
announce_svc: True # If you use FRR/bgpd, you can automatically announce service IPs on workers
dns_addon: True #Or false if you don't want the DNS cluster add-on. NEW: coreDNS will be installed instead of Kube-Dns
cluster_dns: 85.85.85.85
cluster_domain: cluster.local # Not totally supported for now
cluster_cidr: 172.16.0.0/16
proxy_mode: ipvs #ipvs or iptables
install_docker_ce: False #Docker replaced by containerd/runc
install_istio: False # Istio 0.8.0 is clearly not production ready -> Have to bump to v1.0 to try
network_policies: True #Use of kubefw to be able to leverage Network policies
kubefw_deploy: https://raw.githubusercontent.com/jpmondet/kubefw/master/k8s-deploy.yaml
#
## Misc for certificates
#
cluster_name: MyK8sCluster
country: the
locality: automated
organization: way
organizationalUnit : in
state: ansible

